/**
 * Advanced Sovereign Report — Road Section — Your Four Challenges
 *
 * Deepens the base report's brief Challenge-cycle treatment into a full
 * page: all four of the reader's Challenges stacked in the same phase order
 * as their Pinnacles (Page06Pinnacles.tsx), each with its recurring test/
 * blind spot and its resolving "key to the castle" (CHALLENGE_CONTENT in
 * road-content.ts) — plus a dynamic closing insight on how the reader's
 * currently active Pinnacle and Challenge interact, generated by
 * getPinnacleChallengeInteraction().
 *
 * Challenges share the exact same phase timing as Pinnacles (same startAge/
 * endAge windows), so this page borrows the pinnacles array purely for
 * those age ranges — challenges itself is a plain number[4] with no ages of
 * its own. The Third Challenge is conventionally the lifelong "main"
 * challenge, running as a persistent background theme in addition to its
 * own phase.
 *
 * Each challenge card's test/key text and the closing interaction block
 * are data-dependent, so each gets `wrap={false}` + `minPresenceAhead`
 * per Page05Transits.tsx's documented fix for the same orphan-blank-page
 * failure mode — see CARD_MIN_PRESENCE_AHEAD's docblock in PageComponents.tsx.
 */

import React from 'react';
import { Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import { TechnicalLines, CARD_MIN_PRESENCE_AHEAD } from '../../shared/PageComponents';
import { C, F, PAGE } from '../../tokens';
import { CHALLENGE_CONTENT, getPinnacleChallengeInteraction } from './road-content';
import type { ReportData } from '../../tokens';

const S = StyleSheet.create({
  page: { paddingTop: 0, paddingLeft: 0, paddingRight: 0, paddingBottom: PAGE.marginV, backgroundColor: '#F5F5F3', fontFamily: F.sans }, // QA fix: explicit edges, no padding shorthand (see Page05Transits.tsx)
  emeraldLine: { width: PAGE.width, height: 1.5, backgroundColor: C.emerald },
  content: { flex: 1, paddingHorizontal: PAGE.marginH, paddingTop: 30 },

  sectionTag: {
    fontFamily: F.sans, fontSize: 8.5, fontWeight: 500,
    letterSpacing: 2.5, color: C.parchmentFaint, textTransform: 'uppercase', marginBottom: 8,
  },
  heading: {
    fontFamily: F.display, fontSize: 22, fontWeight: 400, color: C.base, lineHeight: 1.15, marginBottom: 8,
  },
  subheading: {
    fontFamily: F.sans, fontSize: 10.5, fontWeight: 300, color: C.parchmentFaint,
    lineHeight: 1.5, marginBottom: 12, maxWidth: 440,
  },
  headingRule: { width: PAGE.contentWidth, height: 0.5, backgroundColor: C.base, opacity: 0.1, marginBottom: 12 },

  stack: { gap: 6 },
  card: {
    padding: 9, backgroundColor: '#FFFFFF',
    borderWidth: 0.5, borderColor: 'rgba(13,13,14,0.12)', borderStyle: 'solid',
  },
  cardCurrent: { borderColor: C.emerald, borderWidth: 1 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 5 },
  numberBadge: { fontFamily: F.display, fontSize: 18, fontWeight: 700, color: C.emerald, width: 30 },
  headerText: { flex: 1 },
  phaseLabel: {
    fontFamily: F.sans, fontSize: 7.5, fontWeight: 500, letterSpacing: 1.4,
    textTransform: 'uppercase', color: C.base, opacity: 0.55,
  },
  ageRange: { fontFamily: F.sans, fontSize: 7.5, fontWeight: 300, color: C.parchmentFaint, marginTop: 1 },
  currentBadge: {
    fontFamily: F.sans, fontSize: 6.5, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase',
    color: '#FFFFFF', backgroundColor: C.emerald, paddingVertical: 3, paddingHorizontal: 7,
  },
  testText: {
    fontFamily: F.sans, fontSize: 8.5, fontWeight: 300, color: C.base, lineHeight: 1.42, opacity: 0.85, marginBottom: 4,
  },
  keyRow: { flexDirection: 'row', gap: 6, paddingTop: 5, borderTopWidth: 0.5, borderTopColor: 'rgba(13,13,14,0.08)' },
  keyLabel: {
    fontFamily: F.sans, fontSize: 6.5, fontWeight: 500, letterSpacing: 1.2,
    textTransform: 'uppercase', color: C.emeraldDim, width: 50,
  },
  keyText: { flex: 1, fontFamily: F.sans, fontSize: 8, fontWeight: 300, color: C.base, lineHeight: 1.4, opacity: 0.8 },

  interactionBlock: {
    marginTop: 14, padding: 15, backgroundColor: '#EFF5EF',
    borderLeftWidth: 2, borderLeftColor: C.emerald, borderLeftStyle: 'solid', gap: 4,
  },
  interactionLabel: {
    fontFamily: F.sans, fontSize: 7.5, fontWeight: 500, letterSpacing: 1.6,
    textTransform: 'uppercase', color: C.emeraldDim,
  },
  interactionText: {
    fontFamily: F.sans, fontSize: 9.5, fontWeight: 300, color: C.base, lineHeight: 1.55, fontStyle: 'italic',
  },

  missingBlock: {
    padding: 20, backgroundColor: '#F5F3EE',
    borderWidth: 0.5, borderColor: 'rgba(13,13,14,0.1)', gap: 8,
  },
  missingTitle: { fontFamily: F.display, fontSize: 16, fontWeight: 400, color: C.base, lineHeight: 1.2 },
  missingText: { fontFamily: F.sans, fontSize: 10.5, fontWeight: 300, color: C.base, lineHeight: 1.5, opacity: 0.82 },

  footer: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    paddingHorizontal: PAGE.marginH, paddingBottom: 24,
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
  },
  footerText: { fontFamily: F.sans, fontSize: 7, letterSpacing: 1.2, color: C.parchmentFaint, textTransform: 'uppercase' },
  pageNum: { fontFamily: F.sans, fontSize: 7, color: C.parchmentFaint },
});

const CHALLENGE_LABELS = ['First Challenge', 'Second Challenge', 'Third Challenge · Lifelong', 'Fourth Challenge'];

function formatAgeRange(startAge: number, endAge: number | null): string {
  return endAge === null ? `Age ${startAge}+` : `Age ${startAge}–${endAge}`;
}

interface Props {
  data: Pick<ReportData, 'pinnacles' | 'challenges' | 'currentPinnacleIndex'>;
}

export default function Page07Challenges({ data }: Props) {
  const hasChallenges =
    Array.isArray(data.challenges) && data.challenges.length === 4 &&
    Array.isArray(data.pinnacles) && data.pinnacles.length === 4;

  const currentPinnacle = hasChallenges ? data.pinnacles[data.currentPinnacleIndex] : undefined;
  const currentChallenge = hasChallenges ? data.challenges[data.currentPinnacleIndex] : undefined;
  const interaction =
    currentPinnacle && currentChallenge !== undefined
      ? getPinnacleChallengeInteraction(currentPinnacle.number, currentChallenge)
      : null;

  return (
    <Page size="LETTER" style={S.page}>
      <TechnicalLines />

      <View style={S.emeraldLine} />
      <View style={S.content}>
        <Text style={S.sectionTag}>Advanced Sovereign Report · The Road</Text>
        <Text style={S.heading}>Your Four Challenges</Text>
        <Text style={S.subheading}>
          Where your Pinnacles are the climate, your Challenges are the internal friction —
          the specific test each phase is quietly asking you to pass.
        </Text>
        <View style={S.headingRule} />

        {hasChallenges ? (
          <>
            <View style={S.stack}>
              {data.challenges.map((n, i) => {
                const content = CHALLENGE_CONTENT[n];
                const isCurrent = i === data.currentPinnacleIndex;
                const p = data.pinnacles[i];
                if (!content || !p) return null;
                return (
                  <View
                    style={[S.card, isCurrent ? S.cardCurrent : {}]}
                    key={i}
                    wrap={false}
                    minPresenceAhead={CARD_MIN_PRESENCE_AHEAD}
                  >
                    <View style={S.cardHeaderRow}>
                      <Text style={S.numberBadge}>{n}</Text>
                      <View style={S.headerText}>
                        <Text style={S.phaseLabel}>{CHALLENGE_LABELS[i]}</Text>
                        <Text style={S.ageRange}>{formatAgeRange(p.startAge, p.endAge)}</Text>
                      </View>
                      {isCurrent && <Text style={S.currentBadge}>Now</Text>}
                    </View>
                    <Text style={S.testText}>{content.test}</Text>
                    <View style={S.keyRow}>
                      <Text style={S.keyLabel}>Key</Text>
                      <Text style={S.keyText}>{content.key}</Text>
                    </View>
                  </View>
                );
              })}
            </View>

            {interaction && (
              <View style={S.interactionBlock} wrap={false} minPresenceAhead={CARD_MIN_PRESENCE_AHEAD}>
                <Text style={S.interactionLabel}>Right Now: How Your Pinnacle and Challenge Interact</Text>
                <Text style={S.interactionText}>{interaction}</Text>
              </View>
            )}
          </>
        ) : (
          <View style={S.missingBlock}>
            <Text style={S.missingTitle}>Challenge Data Unavailable</Text>
            <Text style={S.missingText}>
              Your Challenge cycles are calculated from your full birth date. This layer will populate
              once that data is on file.
            </Text>
          </View>
        )}
      </View>

      <View style={S.footer} fixed>
        <Text style={S.footerText}>T3D Advanced Sovereign Report</Text>
        <Text style={S.pageNum} render={({ pageNumber }) => pageNumber} />
      </View>
    </Page>
  );
}
